<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>Page Analyzer</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
</head>
<body class="min-vh-100 d-flex flex-column">

<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/urls">Сайты</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-1 bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">
                    Бесплатно проверяйте сайты на SEO пригодность
                </p>
                <form class="row" action="/urls" method="post">
                    <div class="col-8">
                        <label class="visually-hidden">URL</label>
                        <?php if (in_array('Name is required', $errors)): ?>
                            <input class="form-control is-invalid form-control-lg rounded-1" type="text"
                                   name="url[name]"
                                   placeholder="https://www.example.com">
                            <div class="invalid-feedback">
                                URL не должен быть пустым
                            </div>
                        <?php elseif (!empty($errors)): ?>
                            <input class="form-control is-invalid form-control-lg rounded-1" type="text"
                                   name="url[name]"
                                   value="<?= htmlspecialchars($name); ?>">
                            <div class="invalid-feedback">
                                Некорректный URL
                            </div>
                        <?php else: ?>
                            <input class="form-control form-control-lg rounded-1" type="text"
                                   name="url[name]"
                                   placeholder="https://www.example.com">
                        <?php endif; ?>
                    </div>
                    <div class="col-2">
                        <button class="btn btn-primary rounded-1 btn-lg ms-3 px-5 text-uppercase mx-3" type="submit">
                            Проверить
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

<footer class="border-top mt-5 py-3 flex-shrink-0">
    <div class="container-lg">
        <div class="text-center">
            <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
        </div>
    </div>

</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>