<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>Анализатор страниц</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
</head>
<body class="min-vh-100 d-flex flex-column">

<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="submit" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/urls">Сайты</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<?php if (isset($flash['success'])): ?>
    <div class="alert alert-success" role="alert"><?= htmlspecialchars($flash['success'][0]); ?></div>
<?php elseif (isset($flash['danger'])): ?>
    <div class="alert alert-danger" role="alert"><?= htmlspecialchars($flash['danger'][0]); ?></div>
<?php elseif (isset($flash['warning'])): ?>
    <div class="alert alert-warning" role="alert"><?= htmlspecialchars($flash['warning'][0]); ?></div>
<?php endif ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: <?= htmlspecialchars($url['name']); ?></h1>
        <table class="table table-bordered table-hover text-nowrap" data-test="url">
            <tbody>
            <tr>
                <td>ID</td>
                <td><?= htmlspecialchars($url['id']) ?></td>
            </tr>
            <tr>
                <td>Имя</td>
                <td><?= htmlspecialchars($url['name']) ?></td>
            </tr>
            <tr>
                <td>Дата создания</td>
                <td><?= htmlspecialchars($url['created_at']) ?></td>
            </tr>
            </tbody>
        </table>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form class="mb-3" method="post" action="/urls/<?= htmlspecialchars($url['id']) ?>/checks">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover" data-test="checks">
            <thead>
            <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($checks as $check): ?>
            <tr>
                <td><?= htmlspecialchars($check['id']) ?></td>
                <td><?= htmlspecialchars($check['status_code']) ?></td>
                <td><?= htmlspecialchars($check['h1']) ?></td>
                <td><?= htmlspecialchars($check['title']) ?></td>
                <td><?= htmlspecialchars($check['description']) ?></td>
                <td><?= htmlspecialchars($check['created_at']) ?></td>
            </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</main>

<footer class="border-top mt-5 py-3 flex-shrink-0">
    <div class="container-lg">
        <div class="text-center">
            <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
        </div>
    </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>